In [1]:
import numpy as np

In [6]:
# creating identity matrix
arr=np.identity(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
# arange ---> array-range (same as python)
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
arr=np.arange(10,25)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
arr=np.arange(1,20,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
#use to make equi-distance between the elements
arr=np.linspace(0,20,10)
arr

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [13]:
# copy ---> copy from one var to another 
arr1=arr.copy()
print(arr1)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [14]:
del arr

In [15]:
print(arr)

NameError: name 'arr' is not defined

In [16]:
print(arr1)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


# Numpy Properties & Attributes

In [48]:
#shape ----> find the shape of array (return dimension)
arr=np.arange(5)
print(arr)
print(arr.shape)

[0 1 2 3 4]
(5,)


In [49]:
arr=np.zeros((4,3))
print(arr)
print(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(4, 3)


In [50]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(arr)
print(arr.shape) #(2 matrices, 2 rows, 2 columns )

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [51]:
# ndim ---> returns the dimension
arr.ndim

3

In [52]:
# shape ---> retunr total number of elements
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
arr.size

12

In [53]:
# dtype ---> returns data type
print(arr)
print(arr.dtype)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
int32


In [55]:
# astype ---> use to convert datatype
print(arr)
print(arr.dtype)

arr=arr.astype('float64')
print("Permanent change\n", arr)
print(arr.dtype)

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
float64
Permanent change
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
float64


# Indexing & Slicing In Numpy

In [69]:
arr=np.arange(24)
print(arr)

# indexing
print(arr[11]) #positive
print(arr[-16]) #negative

#slicing(start,end,jump)
print(arr[5:15])
print(arr[-17:-7])
print(arr[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
11
8
[ 5  6  7  8  9 10 11 12 13 14]
[ 7  8  9 10 11 12 13 14 15 16]
[23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [76]:
arr=np.arange(24).reshape(8,3)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [77]:
arr=np.arange(24).reshape(2,4,3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [81]:
arr=np.arange(60).reshape(10,3,2)
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]

 [[30 31]
  [32 33]
  [34 35]]

 [[36 37]
  [38 39]
  [40 41]]

 [[42 43]
  [44 45]
  [46 47]]

 [[48 49]
  [50 51]
  [52 53]]

 [[54 55]
  [56 57]
  [58 59]]]


In [91]:
# multidimensional indexing & slicing
arr=np.arange(24).reshape(6,4)
print(arr)

#indexing
print(arr[3]) #return row
print(arr[4][2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[12 13 14 15]
18


In [101]:
#(row:row , col:col)
#slicing (2 row to 5 row)
print(arr[2:4,2:4])



[[10 11]
 [14 15]]


In [102]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [104]:
print(arr[1:4,1:3])

[[ 5  6]
 [ 9 10]
 [13 14]]


In [106]:
print(arr[3:5,0:3])

[[12 13 14]
 [16 17 18]]


In [108]:
arr=np.arange(32).reshape(2,4,4) #(block, row, col)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [114]:
#indexing
print(arr[1][3][3])

31


In [115]:
arr=np.arange(32).reshape(4,4,2) #(block, row, col)
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]


In [119]:
print(arr[2][2][1])

21


In [122]:
print(arr[3][1][0])

26


In [123]:
arr=np.arange(108).reshape(3,12,3) #(block, row, col)
print(arr)

[[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]
  [ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]
  [ 30  31  32]
  [ 33  34  35]]

 [[ 36  37  38]
  [ 39  40  41]
  [ 42  43  44]
  [ 45  46  47]
  [ 48  49  50]
  [ 51  52  53]
  [ 54  55  56]
  [ 57  58  59]
  [ 60  61  62]
  [ 63  64  65]
  [ 66  67  68]
  [ 69  70  71]]

 [[ 72  73  74]
  [ 75  76  77]
  [ 78  79  80]
  [ 81  82  83]
  [ 84  85  86]
  [ 87  88  89]
  [ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 100 101]
  [102 103 104]
  [105 106 107]]]


In [124]:
print(arr[1][6][1])

55


In [125]:
print(arr[2][11][0])

105


In [126]:
print(arr[2][6][2])

92


In [127]:
print(arr[0][11][0])

33
