In [6]:
import numpy as np 

In [7]:
arr = np.array([1,2,3,4,])
print(arr)

[1 2 3 4]


Scalar Operation on matrices

In [18]:
print(arr+2)
print(arr-2)
print(arr*2)
print(arr/2)
print(arr**2)
print(arr%2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[1 0 1 0]


In [39]:
##Array to array operation
#array follow element wise operation

In [40]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [33]:
print(arr1+arr2)
print(arr1-arr2)
print(arr2-arr1)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)
print(arr2%arr1)

[ 6  8 10 12]
[-4 -4 -4 -4]
[4 4 4 4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[1 2 3 4]
[0 0 1 0]


In [32]:
print(1/5)
print(1%5)
print(2%6)


0.2
1
2


In [38]:
#cant run because shape should be same. 
arr3 = np.array([1,2,3,4])
arr4 = np.array([5,6,7])

print(arr3%arr4)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [41]:
#Aggregation operation in numpy

In [52]:
arr = np.array([10,20,30,40])
print(arr.sum())# return the total sum of an array
print(arr.mean())# return the  mean(average) of array elements
print(arr.max()) # return the largest element of an array
print(arr.min()) # return the smallest value of an array
print(arr.std())
print(arr.var())

100
25.0
40
10
11.180339887498949
125.0


In [48]:
print((10+20+30+40)/4)

25.0


In [51]:
arr_st = np.array([22,24,26,28])
print(arr_st.mean())
print(arr_st.std())

25.0
2.23606797749979


In [53]:
arr_n = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr_n.mean())

3.5


In [54]:
print((1+2+3+4+5+6)/6)

3.5


In [55]:
# When we want the fixed colum or row operation, we use axis

In [59]:
print(arr_n.sum(axis=0))
print(arr_n.sum(axis=1))
print(arr_n.mean(axis=1))
print(arr_n.min(axis=1))
print(arr_n.max(axis=1))
print(arr_n.std(axis=1))
print(arr_n.var(axis=1))

[5 7 9]
[ 6 15]
[2. 5.]
[1 4]
[3 6]
[0.81649658 0.81649658]
[0.66666667 0.66666667]


In [60]:
#logical operator

In [68]:
arr = np.array([10,20,30,40,50])
print(arr>25) # for check condintion and return true or false based on condition
print(arr[arr>25])
print(arr[arr<35])
print(arr[arr%2 == 2])

[False False  True  True  True]
[30 40 50]
[10 20 30]
[]


In [72]:
print(arr[(arr>20)&(arr<50)])
print(arr[(arr>15)|(arr<45)])

[30 40]
[10 20 30 40 50]
